# Generated by Django 2.1.7 on 2019-03-05 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='member_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MDM.member')),
            ],
        ),
        migrations.CreateModel(
            name='member_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='主数据表',
            fields=[
                ('内码', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('对象UUID', models.CharField(max_length=36)),
                ('属性名称', models.CharField(max_length=256)),
                ('属性值UUID', models.CharField(max_length=36, null=True)),
                ('属性值', models.CharField(max_length=256, null=True)),
                ('代替内码', models.BigIntegerField(default=0)),
                ('属性序号', models.DecimalField(decimal_places=6, default=1.0, max_digits=19)),
                ('更新人', models.CharField(max_length=256)),
                ('更新时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('更新时间',),
            },
        ),
        migrations.AddField(
            model_name='member',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDM.member_type'),
        ),
    ]
