# Generated by Django 2.1.7 on 2019-03-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDM', '0002_tasklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='computer_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='os',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='path_info',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='remote_add',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='remote_user',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='request_method',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
