# Generated by Django 2.1.7 on 2019-03-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDM', '0003_auto_20190309_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='parameter',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='task_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
