# Generated by Django 2.1.7 on 2019-03-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDM', '0004_auto_20190309_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=256, null=True)),
                ('os', models.CharField(max_length=256, null=True)),
                ('request_method', models.CharField(max_length=128, null=True)),
                ('path_info', models.CharField(max_length=256, null=True)),
                ('remote_add', models.CharField(max_length=256, null=True)),
                ('remote_user', models.CharField(max_length=256, null=True)),
                ('log_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='computer_name',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='os',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='path_info',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='remote_add',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='remote_user',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='request_method',
        ),
    ]
